services:
  codecloud_shopify.store_manager:
      alias: repository.shop #todo make this configurable

  codecloud_shopify.controller.oauth:
      public: false
      class: CodeCloud\Bundle\ShopifyBundle\Controller\OAuthController
      arguments:
          - "@router"
          - "%codecloud_shopify.oauth%"
          - "@codecloud_shopify.http.client"
          - "@codecloud_shopify.store_manager"

  codecloud_shopify.http.client:
      class: GuzzleHttp\Client

  codecloud_shopify.http.client_factory:
      public: false
      class: CodeCloud\Bundle\ShopifyBundle\Api\HttpClientFactory

  codecloud_shopify.shopify_api_factory:
      class: CodeCloud\Bundle\ShopifyBundle\Api\ShopifyApiFactory
      arguments:
          - "@repository.shop"
          - "@codecloud_shopify.http.client_factory"

  codecloud_shopify.signer:
      public: false
      class: CodeCloud\Bundle\ShopifyBundle\Security\HmacSignature
      arguments:
          - "%codecloud_shopify%"

  codecloud_shopify.oauth.authenticator:
      public: false
      class: CodeCloud\Bundle\ShopifyBundle\Security\OAuthAuthenticator
      arguments:
          - "@codecloud_shopify.signer"
          - "@codecloud_shopify.store_manager"

  codecloud_shopify.provider.store:
      public: false
      class: CodeCloud\Bundle\ShopifyBundle\Security\ShopifyStoreProvider
      arguments:
          - "@codecloud_shopify.store_manager"

#  codecloud_shopify.twig.extension.current_shopify_store:
#    class: CodeCloud\Bundle\ShopifyBundle\Twig\Extension\ShopifyStore
#    tags:
#      - { name: twig.extension }
#    calls:
#      - [setContainer, ["@service_container"]]
