imports:
    - { resource: mappers.yml }

services:
  codecloud_shopify.controller.oauth:
      class: CodeCloud\Bundle\ShopifyBundle\Controller\OAuthController
      arguments:
          - "@router"
          - "%codecloud_shopify.oauth%"
          - "@codecloud_shopify.http.client"
          - "@repository.shop" #todo make this configurable

  codecloud_shopify.http.client_factory:
    class: CodeCloud\Bundle\ShopifyBundle\Api\HttpClientFactory

  codecloud_shopify.http.client:
      class: GuzzleHttp\Client

  codecloud_shopify.http.authorized_client:
    class: GuzzleHttp\Client
    factory: 'codecloud_shopify.http.client_factory:createHttpClient'

  codecloud_shopify.client:
    class: CodeCloud\Bundle\ShopifyBundle\Api\ShopifyApiClient
    arguments:
      - "@codecloud_shopify.http.authorized_client"

  codecloud_shopify.signer:
    class: CodeCloud\Bundle\ShopifyBundle\Auth\HmacSignature
    arguments:
      - "%codecloud_shopify%"

  codecloud_shopify.oauth.authenticator:
    class: CodeCloud\Bundle\ShopifyBundle\Auth\IncomingApiRequest\OAuthAuthenticator
    arguments:
      - "@codecloud_shopify.signer"
      - "@repository.shop" #todo make this configurable

  codecloud_shopify.provider.store:
    class: CodeCloud\Bundle\ShopifyBundle\Auth\Provider\ShopifyStoreProvider
    arguments:
      - "@repository.shop" #todo make this configurable

  codecloud_shopify.twig.extension.current_shopify_store:
    class: CodeCloud\Bundle\ShopifyBundle\Twig\Extension\ShopifyStore
    tags:
      - { name: twig.extension }
    calls:
      - [setContainer, ["@service_container"]]
